#Robocode Robot
#Wed Nov 16 08:12:35 CET 2011
robot.classname=pez.rumble.CassiusClay
robot.author.name=PEZ
robocode.version=1.7.3.2
robot.include.source=true
robot.version=2rho.02no
robot.description=Float like a butterfly\!\nSting like a bee\!
robot.java.source.included=true
robot.webpage=http\://robowiki.net/?CassiusClay
